name: deploy and check Lighthouse 
on: [push]

jobs:
  # https://github.com/amondnet/now-deployment/blob/master/.github/workflows/example-angular.yml
  deploy-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install node_modules
        run: npm install
      - name: deploy to dev.julianehendershot.com
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: npm run deploy:dev
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://dev.julianehendershot.com/en'
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "100"
          minBestPracticesScore: "100"
          minPerformanceScore: "100"
          minProgressiveWebAppScore: "56"
          minSeoScore: "90"
